# Generated by Django 3.2.9 on 2021-11-25 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20211121_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='project.project'),
        ),
    ]
